version: '3.5'

services:
    app:
        container_name: mv-photo-frame
        build:
            context: .
            args:
                - TIMEZONE=${TIMEZONE}
        image: marcv/mv-photo-frame
        environment:
            - BASE_URL=${BASE_URL}
            - FORMAT_OUTPUT=${FORMAT_OUTPUT}
            - RSS_TITLE=${RSS_TITLE}
            - RSS_LINK=${RSS_LINK}
            - RSS_DESCRIPTION=${RSS_DESCRIPTION}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - PASSWORD=${PASSWORD}
            - DIR=${DIR}
            - S3_BUCKET_NAME=${S3_BUCKET_NAME}
            - S3_BUCKET_REGION=${S3_BUCKET_REGION}
        ports:
            - ${WEB_PORT_HOST}:80
        volumes:
            - ${WEB_ROOT_HOST}:/app
        command: php -S 0.0.0.0:80 -t public