version: '3.5'

services:
    app:
        container_name: mv-photo-frame
        build:
            context: .
            args:
                - TIMEZONE=${TIMEZONE}
        image: marcv/mv-photo-frame
        ports:
            - ${WEB_PORT_HOST}:80
        volumes:
            - ${WEB_ROOT_HOST}:/app
        command: php -S 0.0.0.0:80 -t public