version: '3.5'

services:
    php:
        image: mv-photoframe/php
        build:
            context: .
            dockerfile: Dockerfile-php
            args:
                - PATH_TO_ROOT_ON_HOST=/app
        environment:
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        tty: true
        volumes:
            - ${PATH_TO_ROOT_ON_HOST}:/app

    nginx:
        image: mv-photoframe/nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx
        networks:
            default:
                aliases:
                    - ${WEBSITE_HOSTNAME}
        tty: true
        links:
            - php
        ports:
            - ${NGINX_PORT_80_HOST}:80
            - ${NGINX_PORT_443_HOST}:443
        volumes:
            - ${PATH_TO_ROOT_ON_HOST}:/app
            - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
