FROM php:7.2-fpm

ARG PATH_TO_ROOT_ON_HOST

WORKDIR /usr/local/etc

# SETUP SERVER
# =============
RUN apt-get update && apt-get install -y \
    # https://github.com/tianon/docker-brew-debian/issues/49
    gnupg \
    #
    apt-transport-https \
    #
    curl \
    # Needed by Composer
    unzip \
    #
    vim
COPY system/vimrc /etc/vim/vimrc.local
# https://stackoverflow.com/a/42344810/2516943
RUN ln -fs /usr/share/zoneinfo/Europe/Madrid /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata

# INSTALL PHP EXTENSIONS
# ======================
RUN apt-get update \
    \
    # OPCACHE
    && docker-php-ext-install -j$(nproc) opcache

# XDEBUG
RUN pecl channel-update pecl.php.net && pecl install xdebug
COPY php/xdebug.ini php/conf.d/

# CONFIGURATION
# =============
COPY php/php.ini php/
COPY php/*.conf php-fpm.d/

# INSTALL COMPOSER
# (using sync because of https://github.com/docker/docker/issues/9547)
# ================
COPY php/install-composer.sh .
RUN chmod +x install-composer.sh \
    && sync \
    && ./install-composer.sh \
    && rm install-composer.sh

WORKDIR "$PATH_TO_ROOT_ON_HOST"
